version: '3.8'

services:
  smdatabase:
    image: postgres:alpine
    container_name: smDatabase
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: smdatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  prometheusSm:
    image: prom/prometheus
    container_name: prometheusSm
    restart: unless-stopped
    volumes:
      - ./src/main/resources:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - monitoring
    depends_on:
      - postgres-exporter-sm

  grafanaSm:
    image: grafana/grafana-oss
    container_name: grafanaSm
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password
    networks:
      - monitoring
    depends_on:
      - prometheusSm

  postgres-exporter-sm:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter-sm
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:root@smdatabase:5432/smdatabase?sslmode=disable"
    depends_on:
      - smdatabase
    networks:
      - monitoring

volumes:
  postgres_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge
